import {
    Badge,
    Brain,
    Bug,
    Droplet,
    Flame,
    Ghost,
    Leaf,
    Moon,
    Mountain,
    Shield,
    Skull,
    Snowflake,
    Sparkle,
    Sparkles,
    Stone,
    Swords,
    Wind,
    Zap,
} from "lucide-react-native";

export const typeIcons: Record<string, any> = {
  fire: Flame,
  water: Droplet,
  grass: Leaf,
  electric: Zap,
  bug: Bug,
  flying: Wind,
  rock: Stone,
  poison: Skull,
  ground: Mountain,
  ice: Snowflake,
  fighting: Swords,
  psychic: Brain,
  ghost: Ghost,
  dragon: Sparkle,
  dark: Moon,
  steel: Shield,
  fairy: Sparkles,
  normal: Badge,
};
